common:
  property: common value
some:
  property: common value

management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
    jmx:
      domain: "io.spring.lab.${spring.application.name}"
  endpoint:
    health:
      show-details: "always"
  metrics:
    export:
      jmx:
        enabled: false
      graphite:
        enabled: false

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: "http://localhost:9010/eureka"
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    health-check-url-path: "/admin/health"
    status-page-url-path: "/admin/info"
    metadata-map:
      startup: ${random.int}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

feign:
  hystrix:
    enabled: true
