server:
  port: 9010

management:
  server:
    port: 19010

eureka:
  instance:
    hostname: "localhost"
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://${eureka.instance.hostname}:${server.port}/eureka"

spring:
  boot:
    admin:
      context-path: "/ui"
      discovery:
        converter:
          management-context-path: "/admin"
